### ISSUE TITLE
[minor] Incorrect link to knitted book in readme file

### ISSUE THREAD

**Issue by anamartinovici** [alexander-pastukhov/writing-games-with-python-and-psychopy#1]
Hi @alexander-pastukhov 

Thank you for making this, and many other resources openly available. I've been going through [Writing games with Python and PsychoPy](https://alexander-pastukhov.github.io/writing-games-with-python-and-psychopy/index.html) and I find it very useful.

Just a minor issue:
- the readme file in this repository has a link that is pointing to https://alexander-pastukhov.github.io/data-analysis-using-r-for-psychology/. I think the correct link should be https://alexander-pastukhov.github.io/writing-games-with-python-and-psychopy/

I'm only opening one issue, in this repo, but in a similar way the readme file in https://github.com/alexander-pastukhov/data-analysis-using-r-for-psychology points to [Writing games with Python and PsychoPy.](https://alexander-pastukhov.github.io/writing-games-with-python-and-psychopy/)

**Comment by alexander-pastukhov** [comment]
Glad that is helpful! and thank you! (How in the world did I mix them up?)
